"""Dependency-pack manifest for el, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/el.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="el_core_news_sm",
        required=True,
        sentinels=("__init__.py", "el_core_news_sm-3.8.0/config.cfg", "el_core_news_sm-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # el_core_news_sm-3.8.0-py3-none-any.whl
            url="https://github.com/explosion/spacy-models/releases/download/el_core_news_sm-3.8.0/el_core_news_sm-3.8.0-py3-none-any.whl",
            sha256="18df59b7f099a20d6f7cc1f964a57408a4c1663b73b5110932c1ea24f66e3027",
            kind="wheel",
            member_prefix="el_core_news_sm/",
        ),
    ),
)

PACK = LanguagePack(
    code="el",
    approx_download_mb=13,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
