"""Dependency-pack manifest for sv, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/sv.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="sv_core_news_sm",
        required=True,
        sentinels=("__init__.py", "sv_core_news_sm-3.8.0/config.cfg", "sv_core_news_sm-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # sv_core_news_sm-3.8.0-py3-none-any.whl
            url="https://github.com/explosion/spacy-models/releases/download/sv_core_news_sm-3.8.0/sv_core_news_sm-3.8.0-py3-none-any.whl",
            sha256="be4929fb30523dca0b6672f999cdbf4d64f165419f1eed0014ca3a36599b8b4d",
            kind="wheel",
            member_prefix="sv_core_news_sm/",
        ),
    ),
)

PACK = LanguagePack(
    code="sv",
    approx_download_mb=13,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
