"""Dependency-pack manifest for fr, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/fr.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="fr_core_news_sm",
        required=True,
        sentinels=("__init__.py", "fr_core_news_sm-3.8.0/config.cfg", "fr_core_news_sm-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # fr_core_news_sm-3.8.0-py3-none-any.whl
            url="https://github.com/explosion/spacy-models/releases/download/fr_core_news_sm-3.8.0/fr_core_news_sm-3.8.0-py3-none-any.whl",
            sha256="7d6ad14cd5078e53147bfbf70fb9d433c6a3865b695fda2657140bbc59a27e29",
            kind="wheel",
            member_prefix="fr_core_news_sm/",
        ),
    ),
)

PACK = LanguagePack(
    code="fr",
    approx_download_mb=17,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
