"""Dependency-pack manifest for pl, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/pl.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="pl_core_news_sm",
        required=True,
        sentinels=("__init__.py", "pl_core_news_sm-3.8.0/config.cfg", "pl_core_news_sm-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # pl_core_news_sm-3.8.0-py3-none-any.whl
            url="https://github.com/explosion/spacy-models/releases/download/pl_core_news_sm-3.8.0/pl_core_news_sm-3.8.0-py3-none-any.whl",
            sha256="9b536db854b0cdb9132a74f68b392b8112ab6030f971bb03282462362a940dbb",
            kind="wheel",
            member_prefix="pl_core_news_sm/",
        ),
    ),
)

PACK = LanguagePack(
    code="pl",
    approx_download_mb=21,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
