"""Dependency-pack manifest for fi, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/fi.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="fi_core_news_sm",
        required=True,
        sentinels=("__init__.py", "fi_core_news_sm-3.8.0/config.cfg", "fi_core_news_sm-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # fi_core_news_sm-3.8.0-py3-none-any.whl
            url="https://github.com/explosion/spacy-models/releases/download/fi_core_news_sm-3.8.0/fi_core_news_sm-3.8.0-py3-none-any.whl",
            sha256="5b9bd1496f500c1fac98f5e6a5d3913aa502f188c094ecea191dc6b8a81f418d",
            kind="wheel",
            member_prefix="fi_core_news_sm/",
        ),
    ),
)

PACK = LanguagePack(
    code="fi",
    approx_download_mb=15,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
