"""Dependency-pack manifest for sl, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/sl.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="sl_core_news_sm",
        required=True,
        sentinels=("__init__.py", "sl_core_news_sm-3.8.0/config.cfg", "sl_core_news_sm-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # sl_core_news_sm-3.8.0-py3-none-any.whl
            url="https://github.com/explosion/spacy-models/releases/download/sl_core_news_sm-3.8.0/sl_core_news_sm-3.8.0-py3-none-any.whl",
            sha256="d6d11f38c917d59b0fe52a15da09963bdc8011d2be288f75371e734065b6911c",
            kind="wheel",
            member_prefix="sl_core_news_sm/",
        ),
    ),
)

PACK = LanguagePack(
    code="sl",
    approx_download_mb=14,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
