"""Dependency-pack manifest for pt, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/pt.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="pt_core_news_sm",
        required=True,
        sentinels=("__init__.py", "pt_core_news_sm-3.8.0/config.cfg", "pt_core_news_sm-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # pt_core_news_sm-3.8.0-py3-none-any.whl
            url="https://github.com/explosion/spacy-models/releases/download/pt_core_news_sm-3.8.0/pt_core_news_sm-3.8.0-py3-none-any.whl",
            sha256="c304fa04db3af73cd08a250feacf560506e15a2ec2469bd1b09f06847f6b455c",
            kind="wheel",
            member_prefix="pt_core_news_sm/",
        ),
    ),
)

PACK = LanguagePack(
    code="pt",
    approx_download_mb=13,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
