"""Dependency-pack manifest for da, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/da.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="da_core_news_sm",
        required=True,
        sentinels=("__init__.py", "da_core_news_sm-3.8.0/config.cfg", "da_core_news_sm-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # da_core_news_sm-3.8.0-py3-none-any.whl
            url="https://github.com/explosion/spacy-models/releases/download/da_core_news_sm-3.8.0/da_core_news_sm-3.8.0-py3-none-any.whl",
            sha256="8caeb4dc26f56de8abcf70399b202a0b2223d38664b1a59f1cb8db0000808bc9",
            kind="wheel",
            member_prefix="da_core_news_sm/",
        ),
    ),
)

PACK = LanguagePack(
    code="da",
    approx_download_mb=13,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
