"""Dependency-pack manifest for lt, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/lt.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="lt_core_news_sm",
        required=True,
        sentinels=("__init__.py", "lt_core_news_sm-3.8.0/config.cfg", "lt_core_news_sm-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # lt_core_news_sm-3.8.0-py3-none-any.whl
            url="https://github.com/explosion/spacy-models/releases/download/lt_core_news_sm-3.8.0/lt_core_news_sm-3.8.0-py3-none-any.whl",
            sha256="c1f709112fd01771c10fbd2fe7e01d9d65712c8bccd9171065a29f91c9dc151e",
            kind="wheel",
            member_prefix="lt_core_news_sm/",
        ),
    ),
)

PACK = LanguagePack(
    code="lt",
    approx_download_mb=14,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
