"""Dependency-pack manifest for nb, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/nb.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="nb_core_news_sm",
        required=True,
        sentinels=("__init__.py", "nb_core_news_sm-3.8.0/config.cfg", "nb_core_news_sm-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # nb_core_news_sm-3.8.0-py3-none-any.whl
            url="https://github.com/explosion/spacy-models/releases/download/nb_core_news_sm-3.8.0/nb_core_news_sm-3.8.0-py3-none-any.whl",
            sha256="086f2cfcc1568b2ee49a2ab297f7910f2645ae6892f2d5d15d8b077f5d0bd773",
            kind="wheel",
            member_prefix="nb_core_news_sm/",
        ),
    ),
)

PACK = LanguagePack(
    code="nb",
    approx_download_mb=13,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
