"""Dependency-pack manifest for ro, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/ro.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="ro_core_news_sm",
        required=True,
        sentinels=("__init__.py", "ro_core_news_sm-3.8.0/config.cfg", "ro_core_news_sm-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # ro_core_news_sm-3.8.0-py3-none-any.whl
            url="https://github.com/explosion/spacy-models/releases/download/ro_core_news_sm-3.8.0/ro_core_news_sm-3.8.0-py3-none-any.whl",
            sha256="3cebfba2437131efe95345adcc7ea2131e4463915652df9099c577e618460cd9",
            kind="wheel",
            member_prefix="ro_core_news_sm/",
        ),
    ),
)

PACK = LanguagePack(
    code="ro",
    approx_download_mb=13,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
