"""Dependency-pack manifest for nl, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/nl.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="nl_core_news_sm",
        required=True,
        sentinels=("__init__.py", "nl_core_news_sm-3.8.0/config.cfg", "nl_core_news_sm-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # nl_core_news_sm-3.8.0-py3-none-any.whl
            url="https://github.com/explosion/spacy-models/releases/download/nl_core_news_sm-3.8.0/nl_core_news_sm-3.8.0-py3-none-any.whl",
            sha256="a76978477821f213ca76a46c686df1b1d41462905d4868bc53eac086adca8b7e",
            kind="wheel",
            member_prefix="nl_core_news_sm/",
        ),
    ),
)

PACK = LanguagePack(
    code="nl",
    approx_download_mb=13,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
