"""Dependency-pack manifest for hr, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/hr.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="hr_core_news_sm",
        required=True,
        sentinels=("__init__.py", "hr_core_news_sm-3.8.0/config.cfg", "hr_core_news_sm-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # hr_core_news_sm-3.8.0-py3-none-any.whl
            url="https://github.com/explosion/spacy-models/releases/download/hr_core_news_sm-3.8.0/hr_core_news_sm-3.8.0-py3-none-any.whl",
            sha256="393ad455bba13536e6fb257bce2b5ef0253f41c1fb5249d8c16dde6cf116d196",
            kind="wheel",
            member_prefix="hr_core_news_sm/",
        ),
    ),
)

PACK = LanguagePack(
    code="hr",
    approx_download_mb=14,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
