"""Dependency-pack manifest for it, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/it.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="it_core_news_sm",
        required=True,
        sentinels=("__init__.py", "it_core_news_sm-3.8.0/config.cfg", "it_core_news_sm-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # it_core_news_sm-3.8.0-py3-none-any.whl
            url="https://github.com/explosion/spacy-models/releases/download/it_core_news_sm-3.8.0/it_core_news_sm-3.8.0-py3-none-any.whl",
            sha256="3f617bf9a8ae0418953cf1fbf014e10272684c4229e882a7fd748b637d0100bf",
            kind="wheel",
            member_prefix="it_core_news_sm/",
        ),
    ),
)

PACK = LanguagePack(
    code="it",
    approx_download_mb=14,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
