"""Dependency-pack manifest for en, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/en.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="en_core_web_sm",
        required=True,
        sentinels=("__init__.py", "en_core_web_sm-3.8.0/config.cfg", "en_core_web_sm-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # en_core_web_sm-3.8.0-py3-none-any.whl
            url="https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl",
            sha256="1932429db727d4bff3deed6b34cfc05df17794f4a52eeb26cf8928f7c1a0fb85",
            kind="wheel",
            member_prefix="en_core_web_sm/",
        ),
    ),
)

PACK = LanguagePack(
    code="en",
    approx_download_mb=13,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
