"""Dependency-pack manifest for de, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/de.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="de_core_news_sm",
        required=True,
        sentinels=("__init__.py", "de_core_news_sm-3.8.0/config.cfg", "de_core_news_sm-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # de_core_news_sm-3.8.0-py3-none-any.whl
            url="https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.8.0/de_core_news_sm-3.8.0-py3-none-any.whl",
            sha256="fec69fec52b1780f2d269d5af7582a5e28028738bd3190532459aeb473bfa3e7",
            kind="wheel",
            member_prefix="de_core_news_sm/",
        ),
    ),
)

PACK = LanguagePack(
    code="de",
    approx_download_mb=15,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
