"""Dependency-pack manifest for es, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/es.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="es_core_news_sm",
        required=True,
        sentinels=("__init__.py", "es_core_news_sm-3.8.0/config.cfg", "es_core_news_sm-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # es_core_news_sm-3.8.0-py3-none-any.whl
            url="https://github.com/explosion/spacy-models/releases/download/es_core_news_sm-3.8.0/es_core_news_sm-3.8.0-py3-none-any.whl",
            sha256="e451a83d6df79b87e9eed0cb553f03e99e36a3bab18a7b79f0dcfd1fdf875e12",
            kind="wheel",
            member_prefix="es_core_news_sm/",
        ),
    ),
)

PACK = LanguagePack(
    code="es",
    approx_download_mb=13,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
