"""Dependency-pack manifest for ca, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/ca.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="ca_core_news_sm",
        required=True,
        sentinels=("__init__.py", "ca_core_news_sm-3.8.0/config.cfg", "ca_core_news_sm-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # ca_core_news_sm-3.8.0-py3-none-any.whl
            url="https://github.com/explosion/spacy-models/releases/download/ca_core_news_sm-3.8.0/ca_core_news_sm-3.8.0-py3-none-any.whl",
            sha256="e214211aa8da91c24ebdc453c2aa5f54fac09f44e01e65bcbdd3b0a5cb94d809",
            kind="wheel",
            member_prefix="ca_core_news_sm/",
        ),
    ),
)

PACK = LanguagePack(
    code="ca",
    approx_download_mb=20,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
