"""Dependency-pack manifest for hu, GENERATED by scripts/pin_language_pack.py.

Do not edit by hand: regenerate it, and commit tests/fixtures/language_packs/hu.resolved.json with it.
"""

from __future__ import annotations

from anki_miner.languages.pack_spec import ArtifactSpec, LanguagePack, PackComponent

COMPONENTS = (
    PackComponent(
        import_name="hu_core_news_md",
        required=True,
        sentinels=("__init__.py", "hu_core_news_md-3.8.0/config.cfg", "hu_core_news_md-3.8.0/meta.json"),
        universal=ArtifactSpec(
            # hu_core_news_md-any-py3-none-any.whl
            url="https://huggingface.co/huspacy/hu_core_news_md/resolve/v3.8.0/hu_core_news_md-any-py3-none-any.whl",
            sha256="0fd89c6ccf0efe1d7591910065c3bec4eadb1e25313d6ceea551150832b0f861",
            kind="wheel",
            member_prefix="hu_core_news_md/",
        ),
    ),
)

PACK = LanguagePack(
    code="hu",
    approx_download_mb=128,
    components=COMPONENTS,
    requires=("_spacy",),
)

__all__ = ["PACK"]
