"""Synthetic Japanese text images and clips for the Video OCR tests (no copyrighted footage)."""

from __future__ import annotations

import subprocess
from collections.abc import Sequence
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

import anki_miner

FONT = Path(anki_miner.__file__).parent / "gui" / "resources" / "fonts" / "NotoSansJP-Regular.otf"


def render_line(text: str, *, size: tuple[int, int] = (640, 120), font_px: int = 40) -> np.ndarray:
    """BGR image: white text with a black outline, centred on mid-grey."""
    image = Image.new("RGB", size, (90, 90, 90))
    draw = ImageDraw.Draw(image)
    font = ImageFont.truetype(str(FONT), font_px)
    left, top, right, bottom = draw.textbbox((0, 0), text, font=font)
    xy = ((size[0] - (right - left)) // 2, (size[1] - (bottom - top)) // 2 - top)
    draw.text(xy, text, font=font, fill=(255, 255, 255), stroke_width=3, stroke_fill=(0, 0, 0))
    return np.asarray(image)[:, :, ::-1].copy()


def write_clip(
    path: Path,
    frames: Sequence[np.ndarray],
    *,
    fps: int = 25,
    extra_output_args: Sequence[str] = (),
) -> Path:
    """Encode BGR frames losslessly (ffv1, bgr0) so a decoded pixel equals the written one.

    Frames are streamed to ffmpeg one at a time (never joined), so a clip costs one
    frame of memory. For long flat clips use :func:`color_clip`.
    """
    height, width = frames[0].shape[:2]
    cmd = [
        "ffmpeg",
        "-v",
        "error",
        "-y",
        "-f",
        "rawvideo",
        "-pix_fmt",
        "bgr24",
        "-s",
        f"{width}x{height}",
        "-r",
        str(fps),
        "-i",
        "-",
        *extra_output_args,
        "-c:v",
        "ffv1",
        "-pix_fmt",
        "bgr0",
        str(path),
    ]
    proc = subprocess.Popen(cmd, stdin=subprocess.PIPE)
    assert proc.stdin is not None
    for frame in frames:
        proc.stdin.write(np.ascontiguousarray(frame).tobytes())
    proc.stdin.close()
    assert proc.wait(timeout=60) == 0
    return path


def color_clip(path: Path, *, seconds: int, size: tuple[int, int] = (640, 360), color: str = "0x5a5a5a") -> Path:
    """A flat clip generated by ffmpeg itself (lavfi), for long-duration tests."""
    source = f"color=c={color}:s={size[0]}x{size[1]}:r=25:d={seconds}"
    subprocess.run(
        ["ffmpeg", "-v", "error", "-y", "-f", "lavfi", "-i", source, "-c:v", "ffv1", str(path)],
        check=True,
        timeout=120,
    )
    return path


def solid(color: int, size: tuple[int, int] = (640, 360)) -> np.ndarray:
    """A flat BGR frame; the colour doubles as a code a fake OCR reader can map to text."""
    return np.full((size[1], size[0], 3), color, dtype=np.uint8)
