"""The Anki Miner Note field names, shared by the tests that map onto them."""

from __future__ import annotations

# ~/Projects/anki_miner_note/build/fields.lock, in order (append-only upstream).
AMN_FIELDS = [
    "Expression",
    "ExpressionFurigana",
    "ExpressionReading",
    "ExpressionAudio",
    "SelectionText",
    "MainDefinition",
    "DefinitionPicture",
    "Sentence",
    "SentenceFurigana",
    "SentenceAudio",
    "Picture",
    "Glossary",
    "Hint",
    "IsWordAndSentenceCard",
    "IsClickCard",
    "IsSentenceCard",
    "IsAudioCard",
    "PitchPosition",
    "PitchCategories",
    "Frequency",
    "FreqSort",
    "MiscInfo",
    "SentenceTranslation",
    "Language",
    "Pinyin",
    "Jyutping",
    "Traditional",
    "MeasureWord",
    "Hanja",
    "HanViet",
    "Gender",
    "Article",
    "Plural",
    "PartOfSpeech",
    "AspectPair",
    "Root",
    "Binyan",
    "Transliteration",
    "Romanization",
    "Colloquial",
    "PresentStem",
    "Classifier",
    "Affixes",
    "Formal",
    "Grammar",
    "Segmentation",
]
